package com.el_jumillano.pac.audit.domain;

public enum AuditAction {
    DEPOSIT_DETECTED,
    EXPECTED_FETCHED,
    EXPECTED_UPDATED,
    MANUAL_CHECK_LOADED,
    RECONCILIATION_CREATED,
    RECONCILIATION_CALCULATED,
    DIFFERENCE_DETECTED,
    ROUTE_PROCESSED,
    ROUTE_CLOSED,
    DEPOSIT_ADJUSTED,
    MINIBANK_ERROR,
    AGUAS_ERROR
}
